import { describe, expect, it } from "vitest";
import { campaignFinancials, computeRevenueSummary, isDeliveryOverdue, isPaymentOverdue, isPublishedWithoutContent, resolveSalesRecord, salesConversions } from "./negocio";
import type { Campaign, CampaignPayment, ContentItem, MetricSnapshot, SalesRecord } from "@/types/domain";

const campaign=(o:Partial<Campaign>={}):Campaign=>({id:"c1",user_id:"u1",name:"Campanha",description:null,brand_name:"Marca",contact_name:null,contact_email:null,contact_phone:null,contact_notes:null,first_contact_date:null,campaign_type:"paid_post",account_id:null,delivery_due_date:null,published_at:null,contracted_fee:null,currency:"BRL",negotiation_status:"approved",contract_status:"signed",delivery_status:"in_production",payment_status:"awaiting_payment",expected_payment_date:null,briefing_url:null,contract_url:null,folder_url:null,publication_url:null,responsible_name:null,notes:null,starts_at:null,ends_at:null,created_at:"2026-09-01T00:00:00Z",updated_at:"2026-09-01T00:00:00Z",archived_at:null,...o});
const payment=(o:Partial<CampaignPayment>={}):CampaignPayment=>({id:"p1",user_id:"u1",campaign_id:"c1",amount:1000,received_amount:null,due_date:null,received_at:null,status:"awaiting_payment",notes:null,created_at:"2026-09-01T00:00:00Z",updated_at:"2026-09-01T00:00:00Z",...o});
const record=(o:Partial<SalesRecord>={}):SalesRecord=>({id:"s1",user_id:"u1",product_id:"pr1",campaign_id:null,content_item_id:"i1",metric_snapshot_id:null,source:"manual",sale_date:"2026-09-01",cta:null,link_clicks:null,leads:null,sales_count:null,revenue:null,notes:null,created_at:"2026-09-01T00:00:00Z",updated_at:"2026-09-01T00:00:00Z",...o});
const snapshot=(o:Partial<MetricSnapshot>={}):MetricSnapshot=>({id:"m1",content_item_id:"i1",user_id:"u1",window_type:"30d",window_start:null,window_end:null,captured_at:"2026-09-01T00:00:00Z",views:null,reach:null,impressions:null,likes:null,comments:null,shares:null,saves:null,replies:null,profile_visits:null,followers_gained:null,link_clicks:null,leads:null,sales:null,revenue:null,average_watch_time_seconds:null,video_duration_seconds:null,three_second_views:null,completed_views:null,retention_rate:null,story_exits:null,taps_forward:null,taps_back:null,created_at:"2026-09-01T00:00:00Z",...o});

describe("financeiro de campanha",()=>{
 it("calcula contratado, múltiplos recebimentos, saldo e vencido",()=>{const c=campaign({contracted_fee:3000});const payments=[payment({id:"a",amount:1000,received_amount:1000,received_at:"2026-09-01T12:00:00Z",status:"paid"}),payment({id:"b",amount:1000,received_amount:400,received_at:"2026-09-02T12:00:00Z",status:"partially_paid",due_date:"2026-09-03"}),payment({id:"c",amount:1000,due_date:"2026-10-01"})];expect(campaignFinancials(c,payments,"2026-09-04")).toEqual({contracted:3000,received:1400,balance:1600,overdue:600})});
 it("não considera recebimento sem confirmação nem parcela cancelada",()=>{const result=campaignFinancials(campaign({contracted_fee:500}),[payment({received_amount:500}),payment({id:"x",received_amount:500,received_at:"2026-09-01T00:00:00Z",status:"canceled"})],"2026-09-04");expect(result.received).toBe(0);expect(result.balance).toBe(500)});
});

describe("fonte de verdade de vendas",()=>{
 it("registro por snapshot deriva números sem usar colunas manuais",()=>{const r=record({source:"metric_snapshot",metric_snapshot_id:"m1"});const e=resolveSalesRecord(r,new Map([["m1",snapshot({link_clicks:100,leads:10,sales:2,revenue:300})]]));expect(e).toMatchObject({linkClicks:100,leads:10,sales:2,revenue:300})});
 it("cada registro é agregado uma vez e receita total não soma snapshot separado",()=>{const r=record({source:"metric_snapshot",metric_snapshot_id:"m1"});const e=resolveSalesRecord(r,new Map([["m1",snapshot({sales:2,revenue:300})]]));const result=computeRevenueSummary([],[],[e],"2026-09-04");expect(result.productRevenue).toBe(300);expect(result.totalRevenue).toBe(300);expect(result.sales).toBe(2)});
 it("preserva zero informado e mantém ausência como null",()=>{const zero=resolveSalesRecord(record({link_clicks:0,leads:0,sales_count:0,revenue:0}),new Map());const absent=resolveSalesRecord(record(),new Map());expect(zero).toMatchObject({linkClicks:0,leads:0,sales:0,revenue:0});expect(absent).toMatchObject({linkClicks:null,leads:null,sales:null,revenue:null})});
 it("conversões exigem denominador válido",()=>{expect(salesConversions({linkClicks:0,leads:3,sales:1,revenue:100})).toEqual({clickToLead:null,clickToSale:null,averageTicket:100});expect(salesConversions({linkClicks:null,leads:3,sales:null,revenue:100}).averageTicket).toBeNull();expect(salesConversions({linkClicks:100,leads:20,sales:4,revenue:200})).toEqual({clickToLead:20,clickToSale:4,averageTicket:50})});
});

describe("alertas e vínculos",()=>{
 it("detecta entrega e pagamento vencidos",()=>{expect(isDeliveryOverdue(campaign({delivery_due_date:"2026-09-03"}),"2026-09-04")).toBe(true);expect(isPaymentOverdue(payment({due_date:"2026-09-03"}),"2026-09-04")).toBe(true);expect(isPaymentOverdue(payment({due_date:"2026-09-03",status:"paid",received_amount:1000,received_at:"2026-09-03T10:00:00Z"}),"2026-09-04")).toBe(false)});
 it("avisa campanha publicada sem conteúdo vinculado",()=>{const c=campaign({delivery_status:"published"});expect(isPublishedWithoutContent(c,[])).toBe(true);expect(isPublishedWithoutContent(c,[{campaign_id:"c1"} as ContentItem])).toBe(false)});
});
