"use server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { parseXlsx, fileHash, MAX_IMPORT_BYTES, ACCEPTED_IMPORT_TYPES } from "@/lib/spreadsheet-import";
import { appSettingsPatchSchema } from "@/lib/validations/configuracoes";
import { instagramAccountSchema } from "@/lib/validations/instagram-accounts";
import type { Json } from "@/types/database";

export type ConfigResult={success?:true;error?:string;batchId?:string;preview?:Json;report?:Json};
async function auth(){const db=await createClient();const{data:{user}}=await db.auth.getUser();if(!user)throw new Error("Sua sessão expirou.");return{db,user}}
const list=(v:FormDataEntryValue|null)=>String(v??"").split("\n").map(x=>x.trim()).filter(Boolean);
/** Número não-negativo, ou `null` quando o campo é deixado em branco — nunca convertido para 0 (ver CLAUDE.md: ausência de dado é null). */
const optionalNonNegativeNumber=(v:FormDataEntryValue|null)=>{const s=String(v??"").trim();return s===""?null:Number(s)};
export async function saveSettingsAction(form:FormData):Promise<ConfigResult>{try{const{db,user}=await auth();let extra:Json;try{extra=JSON.parse(String(form.get("extra")||"{}")) as Json}catch{return{error:"O campo de metas/faixas/pesos avançado não é um JSON válido."}}const values={pillar:list(form.get("pillars")),format:list(form.get("formats")),objective:list(form.get("objectives")),cta:list(form.get("ctas")),priority:list(form.get("priorities"))};const parsed=appSettingsPatchSchema.safeParse({pillars:values.pillar,formats:values.format,objectives:values.objective,ctas:values.cta,priorities:values.priority,weekly_publish_target:optionalNonNegativeNumber(form.get("weekly_publish_target")),stalled_idea_days:Number(form.get("stalled_idea_days")||45),minimum_ideas_per_pillar:Number(form.get("minimum_ideas_per_pillar")||3),extra});if(!parsed.success)return{error:parsed.error.issues[0]?.message??"Dados inválidos."};const patch={...parsed.data,extra:parsed.data.extra as unknown as Json};const{error}=await db.from("app_settings").update(patch).eq("user_id",user.id);if(error)throw error;for(const[kind,items]of Object.entries(values))for(const value of items){const{error:insertError}=await db.from("taxonomy_options").insert({user_id:user.id,kind:kind as "pillar"|"format"|"objective"|"cta"|"priority",value});if(insertError&&insertError.code!=="23505")throw insertError}revalidatePath("/configuracoes");return{success:true}}catch(e){return{error:e instanceof Error?e.message:"Não foi possível salvar."}}}

export async function createInstagramAccountAction(form:FormData):Promise<ConfigResult>{try{const{db,user}=await auth();const parsed=instagramAccountSchema.safeParse({handle:String(form.get("handle")||""),displayName:String(form.get("display_name")||""),isPrimary:form.get("is_primary")==="on"});if(!parsed.success)return{error:parsed.error.issues[0]?.message??"Dados inválidos."};const{handle,displayName,isPrimary}=parsed.data;if(isPrimary){await db.from("instagram_accounts").update({is_primary:false}).eq("user_id",user.id)}const{error}=await db.from("instagram_accounts").insert({user_id:user.id,handle,display_name:displayName,is_primary:isPrimary,connected_at:new Date().toISOString()});if(error)return{error:error.code==="23505"?"Você já tem uma conta cadastrada com esse @.":error.message};revalidatePath("/","layout");return{success:true}}catch(e){return{error:e instanceof Error?e.message:"Não foi possível cadastrar a conta."}}}

export async function saveEditorialListsAction(form:FormData):Promise<ConfigResult>{try{const{db,user}=await auth();const wantedSeries=list(form.get("series"));const{data:series,error}=await db.from("content_series").select("*");if(error)throw error;for(const name of wantedSeries)if(!series?.some(s=>s.name.toLowerCase()===name.toLowerCase()))await db.from("content_series").insert({user_id:user.id,name});for(const item of series??[])if(!wantedSeries.some(n=>n.toLowerCase()===item.name.toLowerCase()))await db.from("content_series").update({archived_at:new Date().toISOString()}).eq("id",item.id);const wantedChecklist=list(form.get("checklist"));const{data:checks,error:checkError}=await db.from("checklist_items").select("*");if(checkError)throw checkError;for(const[label,index]of wantedChecklist.map((v,i)=>[v,i] as const)){const found=checks?.find(c=>c.label.toLowerCase()===label.toLowerCase());if(found)await db.from("checklist_items").update({is_active:true,sort_order:index}).eq("id",found.id);else await db.from("checklist_items").insert({user_id:user.id,label,sort_order:index})}for(const item of checks??[])if(!wantedChecklist.some(v=>v.toLowerCase()===item.label.toLowerCase()))await db.from("checklist_items").update({is_active:false}).eq("id",item.id);revalidatePath("/", "layout");return{success:true}}catch(e){return{error:e instanceof Error?e.message:"Não foi possível salvar séries e checklist."}}}
export async function uploadImportAction(form:FormData):Promise<ConfigResult>{try{const{db,user}=await auth();const file=form.get("file");if(!(file instanceof File))return{error:"Selecione um arquivo XLSX."};if(file.size>MAX_IMPORT_BYTES)return{error:`O arquivo excede ${Math.round(MAX_IMPORT_BYTES/1048576)} MB.`};if(!ACCEPTED_IMPORT_TYPES.includes(file.type)&&!file.name.toLowerCase().endsWith(".xlsx"))return{error:"Formato não permitido. Use .xlsx."};const buffer=Buffer.from(await file.arrayBuffer());const preview=await parseXlsx(buffer);const hash=fileHash(buffer);const accountId=String(form.get("account_id")||"")||null;const{data:existing}=await db.from("import_batches").select("*").eq("user_id",user.id).eq("file_hash",hash).maybeSingle();if(existing)return{batchId:existing.id,preview:existing.payload,report:existing.report,error:existing.status==="completed"?"Este arquivo já foi importado; o lote existente foi preservado.":undefined};const{data,error}=await db.from("import_batches").insert({user_id:user.id,account_id:accountId,file_name:file.name,file_hash:hash,detected_sheets:preview.sheets,mapping:preview.mappings,payload:preview.payload as unknown as Json,report:preview.summary}).select().single();if(error)throw error;return{success:true,batchId:data.id,preview:preview as unknown as Json}}catch(e){return{error:e instanceof Error?e.message:"Falha ao analisar o arquivo."}}}
export async function confirmImportAction(batchId:string):Promise<ConfigResult>{try{const{db,user}=await auth();const{error}=await db.from("import_batches").update({status:"confirmed",confirmed_at:new Date().toISOString()}).eq("id",batchId).eq("user_id",user.id);if(error)throw error;const{data,error:rpcError}=await db.rpc("apply_import_batch",{p_batch_id:batchId});if(rpcError)throw rpcError;revalidatePath("/", "layout");return{success:true,report:data}}catch(e){return{error:e instanceof Error?e.message:"A importação foi desfeita."}}}
export async function replaceTaxonomyAction(kind:string,oldValue:string,newValue:string):Promise<ConfigResult>{try{const{db}=await auth();const{error}=await db.rpc("replace_taxonomy_option",{p_kind:kind,p_old:oldValue,p_new:newValue});if(error)throw error;revalidatePath("/", "layout");return{success:true}}catch(e){return{error:e instanceof Error?e.message:"Não foi possível substituir."}}}
