"use client";
import * as React from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { saveSettingsAction,saveEditorialListsAction,uploadImportAction,confirmImportAction,createInstagramAccountAction } from "@/lib/actions/configuracoes";
import type { AppSettings,InstagramAccount } from "@/types/domain";
const FORMATS=["Reel","Carrossel","Foto","Stories","Live"];
const OBJECTIVES=["alcance","viralização","compartilhamentos","engajamento","crescimento de seguidores","comunidade","autoridade","tráfego","leads","vendas","entretenimento"];
const join=(values:string[],fallback:string[]=[]) => (values.length?values:fallback).join("\n");
export function SettingsWorkspace({settings,accounts,series,checklist}:{settings:AppSettings;accounts:InstagramAccount[];series:string[];checklist:string[]}){
  const[message,setMessage]=React.useState("");const[batch,setBatch]=React.useState<string|null>(null);const[preview,setPreview]=React.useState<Record<string,unknown>|null>(null);const[pending,start]=React.useTransition();
  const extra=settings.extra&&typeof settings.extra==="object"&&!Array.isArray(settings.extra)?settings.extra:{};
  const run=(action:(form:FormData)=>Promise<{error?:string}>,ok:string)=>(form:FormData)=>start(async()=>{const result=await action(form);setMessage(result.error??ok)});
  const upload=(form:FormData)=>start(async()=>{const result=await uploadImportAction(form);setMessage(result.error??"Prévia pronta. Revise e confirme.");setBatch(result.batchId??null);setPreview((result.preview as Record<string,unknown>)??null)});
  const confirm=()=>batch&&start(async()=>{const result=await confirmImportAction(batch);setMessage(result.error??`Importação concluída: ${JSON.stringify(result.report)}`)});
  return <div className="grid gap-6 xl:grid-cols-2"><div className="grid gap-6">
    <Card><CardHeader><CardTitle>Contas do Instagram</CardTitle></CardHeader><CardContent className="grid gap-4"><ul className="grid gap-1 text-sm">{accounts.length===0&&<li className="text-muted-foreground">Nenhuma conta cadastrada ainda.</li>}{accounts.map(a=><li key={a.id} className="flex items-center gap-2">@{a.handle}{a.display_name?` — ${a.display_name}`:""}{a.is_primary&&<span className="rounded bg-muted px-1.5 py-0.5 text-xs">principal</span>}</li>)}</ul><form action={run(createInstagramAccountAction,"Conta cadastrada.")} className="grid grid-cols-2 gap-3"><label className="text-sm col-span-2">@ da conta<Input name="handle" placeholder="seuusuario" required/></label><label className="text-sm">Nome de exibição (opcional)<Input name="display_name"/></label><label className="mt-6 flex items-center gap-2 text-sm"><input type="checkbox" name="is_primary" defaultChecked={accounts.length===0}/>Definir como principal</label><Button disabled={pending} className="col-span-2" variant="outline">Cadastrar conta</Button></form></CardContent></Card>
    <Card><CardHeader><CardTitle>Listas e regras</CardTitle></CardHeader><CardContent><form action={run(saveSettingsAction,"Configurações salvas.")} className="grid gap-4"><p className="text-sm text-muted-foreground">Uma opção por linha. Novas entradas são personalizadas e substituições ficam auditáveis.</p>{[["pillars","Pilares",join(settings.pillars)],["formats","Formatos",join(settings.formats,FORMATS)],["objectives","Objetivos",join(settings.objectives,OBJECTIVES)],["ctas","CTAs",join(settings.ctas)],["priorities","Prioridades",join(settings.priorities,["alta","media","baixa"])]].map(([name,label,value])=><label key={name} className="grid gap-1 text-sm font-medium">{label}<Textarea name={name} defaultValue={value}/></label>)}<div className="grid grid-cols-3 gap-3"><label className="text-sm">Publicações/semana<Input name="weekly_publish_target" type="number" min="0" defaultValue={settings.weekly_publish_target??0}/></label><label className="text-sm">Dias ideia parada<Input name="stalled_idea_days" type="number" min="1" defaultValue={settings.stalled_idea_days}/></label><label className="text-sm">Ideias mín./pilar<Input name="minimum_ideas_per_pillar" type="number" min="0" defaultValue={settings.minimum_ideas_per_pillar}/></label></div><label className="grid gap-1 text-sm font-medium">Metas mensais, faixas e pesos (JSON avançado)<Textarea name="extra" className="min-h-40 font-mono text-xs" defaultValue={JSON.stringify(extra,null,2)}/></label><Button disabled={pending}>Salvar configurações</Button></form></CardContent></Card>
    <Card><CardHeader><CardTitle>Séries e checklist diário</CardTitle></CardHeader><CardContent><form action={run(saveEditorialListsAction,"Séries e checklist salvos.")} className="grid gap-4"><label className="text-sm font-medium">Séries editoriais<Textarea name="series" defaultValue={series.join("\n")}/></label><label className="text-sm font-medium">Checklist padrão<Textarea name="checklist" className="min-h-44" defaultValue={checklist.join("\n")}/></label><Button disabled={pending} variant="outline">Salvar listas editoriais</Button></form><div className="mt-4 flex gap-2"><Button asChild variant="ghost"><Link href="/negocio/produtos">Produtos</Link></Button><Button asChild variant="ghost"><Link href="/negocio/campanhas">Campanhas</Link></Button></div></CardContent></Card>
  </div><div className="grid gap-6"><Card><CardHeader><CardTitle>Importar planilha histórica</CardTitle></CardHeader><CardContent className="grid gap-4"><p className="text-sm text-muted-foreground">Somente XLSX, até 10 MB. Fórmulas, macros, abas ocultas, Cálculos e Exemplos são ignoradas. O arquivo original não é armazenado.</p><form action={upload} className="grid gap-3"><Input name="file" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required/><select name="account_id" className="h-10 rounded-md border bg-background px-3 text-sm"><option value="">Sem conta vinculada</option>{accounts.map(a=><option key={a.id} value={a.id}>@{a.handle}</option>)}</select><Button disabled={pending} variant="outline">Validar e gerar prévia</Button></form>{preview&&<div className="rounded-lg border p-3 text-xs"><pre className="max-h-64 overflow-auto whitespace-pre-wrap">{JSON.stringify(preview,null,2)}</pre><Button className="mt-3" onClick={confirm} disabled={pending}>Confirmo a importação</Button></div>}</CardContent></Card><Card><CardHeader><CardTitle>Exportação e backup</CardTitle></CardHeader><CardContent className="grid gap-3"><Button asChild><a href="/api/backup?format=json">Baixar backup JSON completo</a></Button><Button asChild variant="outline"><a href="/api/backup?format=csv&module=content_items">Exportar conteúdos em CSV</a></Button><p className="text-xs text-muted-foreground">O JSON é versionado. Restauração automática não está habilitada nesta fase; veja a documentação antes de restaurar.</p></CardContent></Card>{message&&<p role="status" className="rounded-lg bg-muted p-3 text-sm">{message}</p>}</div></div>
}
