"use client";

import * as React from "react";
import Link from "next/link";
import { AlertTriangle, ExternalLink, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { StatCard } from "@/components/layout/stat-card";
import { linkContentToCampaign, removeDeliverable, removePayment, saveDeliverable, savePayment } from "@/lib/actions/negocio";
import { campaignFinancials, campaignTimeline, CAMPAIGN_PAYMENT_STATUS_LABELS, CAMPAIGN_TYPE_LABELS, CONTRACT_STATUS_LABELS, DELIVERY_STATUS_LABELS, formatCurrency, isDeliveryOverdue, isPaymentOverdue, isPublishedWithoutContent, NEGOTIATION_STATUS_LABELS, resolveSalesRecord, computeRevenueSummary } from "@/lib/negocio";
import { todayISODate } from "@/lib/dates";
import type { Campaign, CampaignDeliverable, CampaignPayment, ContentItem, MetricSnapshot, Product, SalesRecord } from "@/types/domain";

export function CampaignDetailWorkspace({campaign,initialDeliverables,initialPayments,allContents,products,salesRecords,metricSnapshots}:{campaign:Campaign;initialDeliverables:CampaignDeliverable[];initialPayments:CampaignPayment[];allContents:ContentItem[];products:Product[];salesRecords:SalesRecord[];metricSnapshots:MetricSnapshot[]}){
 const[deliverables,setDeliverables]=React.useState(initialDeliverables);const[payments,setPayments]=React.useState(initialPayments);const[contents,setContents]=React.useState(allContents);const[error,setError]=React.useState<string|null>(null);const today=todayISODate();const linked=contents.filter(c=>c.campaign_id===campaign.id);const available=contents.filter(c=>!c.campaign_id);const financial=campaignFinancials(campaign,payments,today);const snaps=new Map(metricSnapshots.map(s=>[s.id,s]));const effective=salesRecords.map(r=>resolveSalesRecord(r,snaps));const results=computeRevenueSummary([campaign],payments,effective,today);const timeline=campaignTimeline(campaign,deliverables,payments);
 async function attach(id:string){if(!id)return;const r=await linkContentToCampaign(id,campaign.id);if("error"in r)setError(r.error);else setContents(p=>p.map(c=>c.id===id?{...c,campaign_id:campaign.id}:c));}
 async function detach(id:string){const r=await linkContentToCampaign(id,null);if("error"in r)setError(r.error);else setContents(p=>p.map(c=>c.id===id?{...c,campaign_id:null}:c));}
 return <div className="flex flex-col gap-6">{(isDeliveryOverdue(campaign,today)||isPublishedWithoutContent(campaign,contents))?<div className="flex flex-col gap-2 rounded-lg border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">{isDeliveryOverdue(campaign,today)?<span className="flex items-center gap-2"><AlertTriangle className="h-4 w-4"/>A entrega está vencida e ainda não foi concluída.</span>:null}{isPublishedWithoutContent(campaign,contents)?<span className="flex items-center gap-2"><AlertTriangle className="h-4 w-4"/>Campanha publicada sem conteúdo vinculado.</span>:null}</div>:null}{error?<p className="text-sm text-destructive">{error}</p>:null}
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Cachê contratado" value={formatCurrency(financial.contracted,campaign.currency)}/><StatCard label="Recebido" value={formatCurrency(financial.received,campaign.currency)}/><StatCard label="Saldo a receber" value={formatCurrency(financial.balance,campaign.currency)}/><StatCard label="Valor vencido" value={formatCurrency(financial.overdue,campaign.currency)}/></div>
 <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Visão geral</CardTitle></CardHeader><CardContent className="grid gap-3 text-sm sm:grid-cols-2"><Info label="Marca" value={campaign.brand_name}/><Info label="Tipo" value={CAMPAIGN_TYPE_LABELS[campaign.campaign_type]}/><Info label="Negociação" value={NEGOTIATION_STATUS_LABELS[campaign.negotiation_status]}/><Info label="Contrato" value={CONTRACT_STATUS_LABELS[campaign.contract_status]}/><Info label="Entrega" value={DELIVERY_STATUS_LABELS[campaign.delivery_status]}/><Info label="Pagamento" value={CAMPAIGN_PAYMENT_STATUS_LABELS[campaign.payment_status]}/><Info label="Prazo" value={formatDate(campaign.delivery_due_date)}/><Info label="Responsável" value={campaign.responsible_name}/></CardContent></Card><Card><CardHeader><CardTitle>Contato e documentos</CardTitle></CardHeader><CardContent className="flex flex-col gap-2 text-sm"><Info label="Contato" value={campaign.contact_name}/><Info label="E-mail" value={campaign.contact_email}/><Info label="Telefone" value={campaign.contact_phone}/><div className="flex flex-wrap gap-2">{[["Briefing",campaign.briefing_url],["Contrato",campaign.contract_url],["Pasta",campaign.folder_url],["Publicação",campaign.publication_url]].filter((x):x is[string,string]=>Boolean(x[1])).map(([label,url])=><Button key={label} asChild size="sm" variant="outline"><a href={url} target="_blank" rel="noreferrer">{label}<ExternalLink className="ml-1 h-3 w-3"/></a></Button>)}</div>{campaign.notes?<p className="mt-2 whitespace-pre-wrap text-muted-foreground">{campaign.notes}</p>:null}</CardContent></Card></div>
 <Card><CardHeader><CardTitle>Entregáveis</CardTitle></CardHeader><CardContent className="flex flex-col gap-4"><DeliverableForm campaignId={campaign.id} contents={linked} onSaved={d=>setDeliverables(p=>[...p.filter(x=>x.id!==d.id),d])} onError={setError}/>{deliverables.length===0?<p className="text-sm text-muted-foreground">Nenhum entregável estruturado.</p>:deliverables.map(d=><div key={d.id} className="flex flex-col gap-2 rounded-lg border p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{d.quantity}× {d.title}</p><p className="text-xs text-muted-foreground">{d.due_date?`Prazo ${formatDate(d.due_date)} · `:""}{d.status.replaceAll("_"," ")}</p></div><Button size="icon" variant="ghost" aria-label={`Remover ${d.title}`} onClick={async()=>{const r=await removeDeliverable(d.id);if("error"in r)setError(r.error);else setDeliverables(p=>p.filter(x=>x.id!==d.id))}}><Trash2 className="h-4 w-4"/></Button></div>)}</CardContent></Card>
 <Card><CardHeader><CardTitle>Conteúdos vinculados</CardTitle></CardHeader><CardContent className="flex flex-col gap-3"><div className="flex gap-2"><Select aria-label="Selecionar conteúdo para vincular" defaultValue="" onChange={e=>{attach(e.target.value);e.target.value=""}}><option value="">Vincular conteúdo existente…</option>{available.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</Select></div>{linked.length===0?<p className="text-sm text-muted-foreground">Nenhum conteúdo vinculado.</p>:linked.map(c=><div key={c.id} className="flex items-center justify-between gap-2 rounded-lg border p-3"><div><Link href={contentHref(c)} className="font-medium hover:text-primary">{c.title}</Link><p className="text-xs text-muted-foreground">{c.status.replaceAll("_"," ")}</p></div><Button size="sm" variant="ghost" onClick={()=>detach(c.id)}>Desvincular</Button></div>)}</CardContent></Card>
 <Card><CardHeader><CardTitle>Pagamentos e recebimentos</CardTitle></CardHeader><CardContent className="flex flex-col gap-4"><PaymentForm campaignId={campaign.id} onSaved={p=>setPayments(x=>[...x.filter(i=>i.id!==p.id),p])} onError={setError}/>{payments.length===0?<p className="text-sm text-muted-foreground">Nenhuma parcela cadastrada.</p>:payments.map(p=><div key={p.id} className={`flex flex-col gap-2 rounded-lg border p-3 sm:flex-row sm:items-center sm:justify-between ${isPaymentOverdue(p,today)?"border-destructive/40":""}`}><div><p className="font-medium">{formatCurrency(p.amount,campaign.currency)} <span className="font-normal text-muted-foreground">· {CAMPAIGN_PAYMENT_STATUS_LABELS[p.status]}</span></p><p className="text-xs text-muted-foreground">Vencimento {formatDate(p.due_date)} · recebido {formatCurrency(p.received_amount,campaign.currency)}</p></div><Button size="icon" variant="ghost" aria-label="Remover pagamento" onClick={async()=>{const r=await removePayment(p.id);if("error"in r)setError(r.error);else setPayments(x=>x.filter(i=>i.id!==p.id))}}><Trash2 className="h-4 w-4"/></Button></div>)}</CardContent></Card>
 <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Resultados atribuídos</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-3 text-sm"><Info label="Receita de produtos" value={formatCurrency(results.productRevenue)}/><Info label="Vendas" value={results.sales===null?null:results.sales.toLocaleString("pt-BR")}/><Info label="Clique → lead" value={percent(results.clickToLead)}/><Info label="Clique → venda" value={percent(results.clickToSale)}/>{products.length===0?<p className="col-span-2 text-muted-foreground">Cadastre produtos e vendas para atribuir resultados.</p>:null}</CardContent></Card><Card><CardHeader><CardTitle>Cronologia</CardTitle></CardHeader><CardContent className="flex flex-col gap-3">{timeline.map((e,i)=><div key={`${e.date}-${i}`} className="border-l-2 border-primary/30 pl-3"><p className="text-sm font-medium">{e.label}</p><p className="text-xs text-muted-foreground">{formatDateTime(e.date)}</p></div>)}</CardContent></Card></div>
 </div>;
}
function DeliverableForm({campaignId,contents,onSaved,onError}:{campaignId:string;contents:ContentItem[];onSaved:(d:CampaignDeliverable)=>void;onError:(e:string)=>void}){const[open,setOpen]=React.useState(false);if(!open)return <Button variant="outline" className="w-fit gap-1" onClick={()=>setOpen(true)}><Plus className="h-4 w-4"/>Adicionar entregável</Button>;return <form className="grid gap-2 rounded-lg bg-muted/40 p-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await saveDeliverable(Object.fromEntries(f));if("error"in r)onError(r.error);else{onSaved(r.value);setOpen(false)}}}><input type="hidden" name="campaignId" value={campaignId}/><Input name="title" aria-label="Título do entregável" placeholder="Ex.: Reel patrocinado"/><Input name="quantity" type="number" min="1" defaultValue="1" aria-label="Quantidade"/><Select name="contentItemId" aria-label="Conteúdo do entregável"><option value="">Sem conteúdo específico</option>{contents.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</Select><Input name="dueDate" type="date" aria-label="Prazo do entregável"/><input type="hidden" name="status" value="pending"/><Textarea name="notes" placeholder="Observações"/><Button type="submit">Salvar entregável</Button></form>}
function PaymentForm({campaignId,onSaved,onError}:{campaignId:string;onSaved:(p:CampaignPayment)=>void;onError:(e:string)=>void}){const[open,setOpen]=React.useState(false);if(!open)return <Button variant="outline" className="w-fit gap-1" onClick={()=>setOpen(true)}><Plus className="h-4 w-4"/>Adicionar pagamento</Button>;return <form className="grid gap-2 rounded-lg bg-muted/40 p-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();const r=await savePayment(Object.fromEntries(new FormData(e.currentTarget)));if("error"in r)onError(r.error);else{onSaved(r.value);setOpen(false)}}}><input type="hidden" name="campaignId" value={campaignId}/><Input name="amount" type="number" min="0.01" step="0.01" placeholder="Valor da parcela"/><Input name="dueDate" type="date" aria-label="Vencimento"/><Select name="status" defaultValue="awaiting_payment" aria-label="Status do pagamento"><option value="awaiting_invoice">Aguardando nota fiscal</option><option value="awaiting_payment">Aguardando pagamento</option><option value="partially_paid">Pago parcialmente</option><option value="paid">Pago</option><option value="overdue">Atrasado</option><option value="canceled">Cancelado</option></Select><Input name="receivedAmount" type="number" min="0" step="0.01" placeholder="Valor recebido"/><Input name="receivedAt" type="datetime-local" aria-label="Data do recebimento"/><Input name="notes" placeholder="Observação"/><Button type="submit">Salvar pagamento</Button></form>}
function Info({label,value}:{label:string;value:string|null}){return <div><p className="text-xs text-muted-foreground">{label}</p><p>{value||"—"}</p></div>}function formatDate(v:string|null){return v?new Date(`${v.length===10?v+"T12:00:00-03:00":v}`).toLocaleDateString("pt-BR",{timeZone:"America/Sao_Paulo"}):"—"}function formatDateTime(v:string){return new Date(v).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})}function percent(v:number|null){return v===null?"—":`${v.toFixed(1)}%`}function contentHref(c:ContentItem){if(c.status==="scripting"||c.status==="ready_to_record")return`/roteiros/${c.id}`;if(c.status==="editing"||c.status==="awaiting_approval")return`/edicao/${c.id}`;if(c.status==="scheduled")return`/agendamento/${c.id}`;return"/ideias"}
