"use client";

import * as React from "react";
import { useForm } from "react-hook-form";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { saveCampaign } from "@/lib/actions/negocio";
import { CAMPAIGN_PAYMENT_STATUSES, CAMPAIGN_PAYMENT_STATUS_LABELS, CAMPAIGN_TYPES, CAMPAIGN_TYPE_LABELS, CONTRACT_STATUSES, CONTRACT_STATUS_LABELS, DELIVERY_STATUSES, DELIVERY_STATUS_LABELS, NEGOTIATION_STATUSES, NEGOTIATION_STATUS_LABELS } from "@/lib/negocio";
import { toDateTimeLocalInput } from "@/lib/dates";
import type { Campaign, InstagramAccount } from "@/types/domain";

type FormValues = { name:string;brandName:string;campaignType:(typeof CAMPAIGN_TYPES)[number];accountId:string;contactName:string;contactEmail:string;contactPhone:string;contactNotes:string;firstContactDate:string;deliveryDueDate:string;publishedAt:string;contractedFee:string;currency:string;negotiationStatus:(typeof NEGOTIATION_STATUSES)[number];contractStatus:(typeof CONTRACT_STATUSES)[number];deliveryStatus:(typeof DELIVERY_STATUSES)[number];paymentStatus:(typeof CAMPAIGN_PAYMENT_STATUSES)[number];expectedPaymentDate:string;briefingUrl:string;contractUrl:string;folderUrl:string;publicationUrl:string;responsibleName:string;notes:string };
const v=(value:string|null|number)=>value===null?"":String(value);
function defaults(c:Campaign|null):FormValues{return{name:c?.name??"",brandName:c?.brand_name??"",campaignType:c?.campaign_type??"paid_post",accountId:c?.account_id??"",contactName:c?.contact_name??"",contactEmail:c?.contact_email??"",contactPhone:c?.contact_phone??"",contactNotes:c?.contact_notes??"",firstContactDate:c?.first_contact_date??"",deliveryDueDate:c?.delivery_due_date??"",publishedAt:toDateTimeLocalInput(c?.published_at),contractedFee:v(c?.contracted_fee??null),currency:c?.currency??"BRL",negotiationStatus:c?.negotiation_status??"prospecting",contractStatus:c?.contract_status??"not_sent",deliveryStatus:c?.delivery_status??"not_started",paymentStatus:c?.payment_status??"to_be_agreed",expectedPaymentDate:c?.expected_payment_date??"",briefingUrl:c?.briefing_url??"",contractUrl:c?.contract_url??"",folderUrl:c?.folder_url??"",publicationUrl:c?.publication_url??"",responsibleName:c?.responsible_name??"",notes:c?.notes??""};}

export function CampaignFormDialog({open,onOpenChange,campaign,accounts,onSaved}:{open:boolean;onOpenChange:(v:boolean)=>void;campaign:Campaign|null;accounts:InstagramAccount[];onSaved:(v:Campaign)=>void}){
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{campaign?"Editar campanha":"Nova campanha"}</DialogTitle><DialogDescription>Parceria, prazos, contrato e pagamento em um único registro.</DialogDescription></DialogHeader>{open?<CampaignForm key={campaign?.id??"new"} campaign={campaign} accounts={accounts} onSaved={onSaved} close={()=>onOpenChange(false)}/>:null}</DialogContent></Dialog>;
}
function CampaignForm({campaign,accounts,onSaved,close}:{campaign:Campaign|null;accounts:InstagramAccount[];onSaved:(v:Campaign)=>void;close:()=>void}){
 const {register,handleSubmit,formState}=useForm<FormValues>({defaultValues:defaults(campaign)});const[error,setError]=React.useState<string|null>(null);
 async function submit(values:FormValues){setError(null);const result=await saveCampaign(values,campaign?.id);if("error"in result){setError(result.error);return;}onSaved(result.value);close();}
 return <form className="grid gap-5" onSubmit={handleSubmit(submit)}>
  <section className="grid gap-3 sm:grid-cols-2"><Field label="Nome da campanha" id="campaign-name"><Input id="campaign-name" {...register("name")}/></Field><Field label="Marca" id="campaign-brand"><Input id="campaign-brand" {...register("brandName")}/></Field><Field label="Tipo" id="campaign-type"><Select id="campaign-type" {...register("campaignType")}>{CAMPAIGN_TYPES.map(x=><option key={x} value={x}>{CAMPAIGN_TYPE_LABELS[x]}</option>)}</Select></Field><Field label="Conta do Instagram" id="campaign-account"><Select id="campaign-account" {...register("accountId")}><option value="">Sem conta vinculada</option>{accounts.map(a=><option key={a.id} value={a.id}>@{a.handle}</option>)}</Select></Field></section>
  <section className="grid gap-3 border-t pt-4 sm:grid-cols-3"><Field label="Contato" id="campaign-contact"><Input id="campaign-contact" {...register("contactName")}/></Field><Field label="E-mail" id="campaign-email"><Input id="campaign-email" type="email" {...register("contactEmail")}/></Field><Field label="Telefone" id="campaign-phone"><Input id="campaign-phone" {...register("contactPhone")}/></Field><Field label="Primeiro contato" id="campaign-first"><Input id="campaign-first" type="date" {...register("firstContactDate")}/></Field><Field label="Responsável" id="campaign-owner"><Input id="campaign-owner" {...register("responsibleName")}/></Field><Field label="Notas de contato" id="campaign-contact-notes"><Input id="campaign-contact-notes" {...register("contactNotes")}/></Field></section>
  <section className="grid gap-3 border-t pt-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Negociação" id="campaign-neg"><Select id="campaign-neg" {...register("negotiationStatus")}>{NEGOTIATION_STATUSES.map(x=><option key={x} value={x}>{NEGOTIATION_STATUS_LABELS[x]}</option>)}</Select></Field><Field label="Contrato" id="campaign-contract"><Select id="campaign-contract" {...register("contractStatus")}>{CONTRACT_STATUSES.map(x=><option key={x} value={x}>{CONTRACT_STATUS_LABELS[x]}</option>)}</Select></Field><Field label="Entrega" id="campaign-delivery"><Select id="campaign-delivery" {...register("deliveryStatus")}>{DELIVERY_STATUSES.map(x=><option key={x} value={x}>{DELIVERY_STATUS_LABELS[x]}</option>)}</Select></Field><Field label="Pagamento" id="campaign-payment"><Select id="campaign-payment" {...register("paymentStatus")}>{CAMPAIGN_PAYMENT_STATUSES.map(x=><option key={x} value={x}>{CAMPAIGN_PAYMENT_STATUS_LABELS[x]}</option>)}</Select></Field></section>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="Prazo de entrega" id="campaign-due"><Input id="campaign-due" type="date" {...register("deliveryDueDate")}/></Field><Field label="Publicação efetiva" id="campaign-published"><Input id="campaign-published" type="datetime-local" {...register("publishedAt")}/></Field><Field label="Cachê contratado" id="campaign-fee"><Input id="campaign-fee" type="number" min="0" step="0.01" placeholder="—" {...register("contractedFee")}/></Field><Field label="Pagamento previsto" id="campaign-payment-date"><Input id="campaign-payment-date" type="date" {...register("expectedPaymentDate")}/></Field></section>
  <section className="grid gap-3 border-t pt-4 sm:grid-cols-2"><Field label="Briefing" id="campaign-briefing"><Input id="campaign-briefing" type="url" placeholder="https://" {...register("briefingUrl")}/></Field><Field label="Contrato" id="campaign-contract-url"><Input id="campaign-contract-url" type="url" placeholder="https://" {...register("contractUrl")}/></Field><Field label="Pasta de arquivos" id="campaign-folder"><Input id="campaign-folder" type="url" placeholder="https://" {...register("folderUrl")}/></Field><Field label="Publicação" id="campaign-publication"><Input id="campaign-publication" type="url" placeholder="https://" {...register("publicationUrl")}/></Field></section>
  <Field label="Observações" id="campaign-notes"><Textarea id="campaign-notes" rows={3} {...register("notes")}/></Field>
  <input type="hidden" value="BRL" {...register("currency")}/>{error?<p className="text-sm text-destructive">{error}</p>:null}<DialogFooter><Button type="button" variant="outline" onClick={close}>Cancelar</Button><Button type="submit" disabled={formState.isSubmitting}>{formState.isSubmitting?"Salvando...":"Salvar campanha"}</Button></DialogFooter>
 </form>;
}
function Field({label,id,children}:{label:string;id:string;children:React.ReactNode}){return <div className="flex flex-col gap-1.5"><Label htmlFor={id}>{label}</Label>{children}</div>}
