"use client";

import * as React from "react";
import Link from "next/link";
import { AlertTriangle, CalendarClock } from "lucide-react";
import { DateRangePicker, type DateRange } from "@/components/ui/date-range-picker";
import { FilterBar } from "@/components/layout/filter-bar";
import { StatCard } from "@/components/layout/stat-card";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { computeRevenueSummary, filterByPeriod, formatCurrency, isDeliveryOverdue, isPaymentOverdue, resolveSalesRecord } from "@/lib/negocio";
import { getMonthEnd, getMonthStart, todayISODate } from "@/lib/dates";
import type { Campaign, CampaignPayment, ContentItem, Goal, MetricSnapshot, Product, SalesRecord } from "@/types/domain";

export function RevenueWorkspace({campaigns,payments,records,snapshots,products,contents,goals}:{campaigns:Campaign[];payments:CampaignPayment[];records:SalesRecord[];snapshots:MetricSnapshot[];products:Product[];contents:ContentItem[];goals:Goal[]}){
 const today=todayISODate();
 const[period,setPeriod]=React.useState<DateRange>({from:getMonthStart(today),to:getMonthEnd(today)});
 const from=period.from??getMonthStart(today),to=period.to??getMonthEnd(today);
 const snapshotMap=new Map(snapshots.map(s=>[s.id,s]));
 const inPeriod=filterByPeriod(records,from,to).map(r=>resolveSalesRecord(r,snapshotMap));
 const paymentInPeriod=payments.filter(p=>p.received_at&&p.received_at.slice(0,10)>=from&&p.received_at.slice(0,10)<=to);
 const campaignInPeriod=campaigns.filter(c=>{const d=c.first_contact_date??c.starts_at??c.created_at.slice(0,10);return d>=from&&d<=to});
 const summary=computeRevenueSummary(campaignInPeriod,paymentInPeriod,inPeriod,today,payments);
 const productMap=new Map(products.map(p=>[p.id,p.name]));const campaignMap=new Map(campaigns.map(c=>[c.id,c.name]));const contentMap=new Map(contents.map(c=>[c.id,c.title]));const byProduct=groupRevenue(inPeriod,r=>productMap.get(r.record.product_id)??"Produto");const byCampaign=groupRevenue(inPeriod,r=>r.record.campaign_id?(campaignMap.get(r.record.campaign_id)??"Campanha"):"Sem campanha");const byContent=groupRevenue(inPeriod,r=>r.record.content_item_id?(contentMap.get(r.record.content_item_id)??"Conteúdo"):"Sem conteúdo");const upcomingPayments=payments.filter(p=>p.due_date&&p.due_date>=today&&!['paid','canceled'].includes(p.status)).sort((a,b)=>(a.due_date??"").localeCompare(b.due_date??"")).slice(0,5);const upcomingDeliveries=campaigns.filter(c=>c.delivery_due_date&&!['approved','published'].includes(c.delivery_status)).sort((a,b)=>(a.delivery_due_date??"").localeCompare(b.delivery_due_date??"")).slice(0,5);const salesGoal=goals.find(g=>g.metric==="vendas"&&g.period_start<=to&&g.period_end>=from);const revenueGoal=goals.find(g=>g.metric==="receita"&&g.period_start<=to&&g.period_end>=from);
 return <div className="flex flex-col gap-6"><FilterBar><DateRangePicker value={period} onChange={setPeriod}/></FilterBar><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Cachê contratado" value={formatCurrency(summary.contracted)} helpText="Campanhas aprovadas"/><StatCard label="Total recebido" value={formatCurrency(summary.received)}/><StatCard label="Saldo a receber" value={formatCurrency(summary.receivable)}/><StatCard label="Valor vencido" value={formatCurrency(summary.overdue)}/><StatCard label="Receita de produtos" value={formatCurrency(summary.productRevenue)}/><StatCard label="Receita total" value={formatCurrency(summary.totalRevenue)} helpText="Recebimentos + vendas, sem repetir snapshots"/><StatCard label="Vendas" value={summary.sales}/><StatCard label="Ticket médio" value={formatCurrency(summary.averageTicket)}/></div>
 <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Conversão</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-4"><Metric label="Clique → lead" value={pct(summary.clickToLead)}/><Metric label="Clique → venda" value={pct(summary.clickToSale)}/><Metric label="Cliques" value={num(summary.linkClicks)}/><Metric label="Leads" value={num(summary.leads)}/></CardContent></Card><Card><CardHeader><CardTitle>Vendas e receita versus metas</CardTitle></CardHeader><CardContent className="flex flex-col gap-4"><GoalProgress label="Vendas" current={summary.sales} goal={salesGoal}/><GoalProgress label="Receita" current={summary.totalRevenue} goal={revenueGoal} money/></CardContent></Card></div>
 <div className="grid gap-6 lg:grid-cols-3"><Breakdown title="Receita por produto" rows={byProduct}/><Breakdown title="Receita por campanha" rows={byCampaign}/><Breakdown title="Receita por conteúdo" rows={byContent}/></div>
 <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarClock className="h-4 w-4"/>Próximos pagamentos</CardTitle></CardHeader><CardContent className="flex flex-col gap-3">{upcomingPayments.length===0?<p className="text-sm text-muted-foreground">Nenhum pagamento futuro.</p>:upcomingPayments.map(p=><div key={p.id} className={`flex justify-between gap-3 rounded-lg border p-3 text-sm ${isPaymentOverdue(p,today)?"border-destructive":""}`}><span>{campaignMap.get(p.campaign_id)??"Campanha"}<br/><small className="text-muted-foreground">{date(p.due_date)}</small></span><strong>{formatCurrency(Math.max(0,p.amount-(p.received_amount??0)))}</strong></div>)}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><AlertTriangle className="h-4 w-4"/>Próximas entregas</CardTitle></CardHeader><CardContent className="flex flex-col gap-3">{upcomingDeliveries.length===0?<p className="text-sm text-muted-foreground">Nenhuma entrega pendente.</p>:upcomingDeliveries.map(c=><Link key={c.id} href={`/negocio/campanhas/${c.id}`} className={`flex justify-between gap-3 rounded-lg border p-3 text-sm hover:border-primary/40 ${isDeliveryOverdue(c,today)?"border-destructive":""}`}><span>{c.name}<br/><small className="text-muted-foreground">{c.brand_name??"Marca não informada"}</small></span><strong>{date(c.delivery_due_date)}</strong></Link>)}</CardContent></Card></div></div>;
}
function groupRevenue(items:ReturnType<typeof resolveSalesRecord>[],key:(x:ReturnType<typeof resolveSalesRecord>)=>string){const map=new Map<string,{revenue:number;sales:number}>();for(const item of items){const k=key(item),old=map.get(k)??{revenue:0,sales:0};if(item.revenue!==null)old.revenue=Math.round((old.revenue+item.revenue)*100)/100;if(item.sales!==null)old.sales+=item.sales;map.set(k,old)}return [...map.entries()].map(([label,v])=>({label,...v})).sort((a,b)=>b.revenue-a.revenue)}
function Breakdown({title,rows}:{title:string;rows:{label:string;revenue:number;sales:number}[]}){return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="flex flex-col gap-3">{rows.length===0?<p className="text-sm text-muted-foreground">Sem dados no período.</p>:rows.slice(0,8).map(r=><div key={r.label} className="flex justify-between gap-3 text-sm"><span className="truncate">{r.label}</span><span className="shrink-0 font-medium">{formatCurrency(r.revenue)} · {r.sales} venda(s)</span></div>)}</CardContent></Card>}
function GoalProgress({label,current,goal,money=false}:{label:string;current:number|null;goal:Goal|undefined;money?:boolean}){if(!goal||goal.target_value===null)return <p className="text-sm text-muted-foreground">Nenhuma meta de {label.toLowerCase()} para o período.</p>;const percent=current===null?0:Math.min(100,(current/goal.target_value)*100);return <div><div className="mb-1 flex justify-between text-sm"><span>{label}</span><span>{money?formatCurrency(current):num(current)} / {money?formatCurrency(goal.target_value):num(goal.target_value)}</span></div><Progress value={percent}/></div>}
function Metric({label,value}:{label:string;value:string}){return <div><p className="text-xs text-muted-foreground">{label}</p><p className="font-serif text-xl font-semibold">{value}</p></div>}function pct(v:number|null){return v===null?"—":`${v.toFixed(1)}%`}function num(v:number|null){return v===null?"—":v.toLocaleString("pt-BR")}function date(v:string|null){return v?v.split("-").reverse().join("/"):"—"}
